### ISSUE TITLE
Missed lethal

### ISSUE THREAD

**Issue by BongoBengt** [mvegter/OpenAI#10]
In current simulation Bot plays Deckard after bloodlust, thus missing three dmg points.

#######################################################################
start calculations, current time: 14:01:36:0976 V130.1SE control 3000 face 15 twoturnsim 256 ntss 6 16 160 ets 16 secret weight 30 plcmnt
#######################################################################
mana 9/10
emana 10
own secretsCount: 0
enemy secretsCount: 0 ;
player:
0 0 0 1 0 -1 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0
ownhero:
shaman 24 30 0 False False 80 True 0 False 2 0
weapon: 2 1 jadeclaws
ability: True CS2_049 2
osecrets: 
cthunbonus: 0 0 0
jadegolems: 3 5
elementals: 0
quests: None 0 1000 None 0 1000
crystal: 0 0 0
enemyhero:
druid 18 30 7 False False 82
weapon: 0 0 unknown
ability: True CS2_017 0
fatigue: 9 0 14 0
OwnMinions:
jadespirit CFM_715 zp:1 e:28 A:2 H:3 mH:3 rdy:True natt:0
jadegolem CFM_712_t03 zp:2 e:106 A:3 H:3 mH:3 rdy:True natt:0
manatidetotem EX1_575 zp:3 e:25 A:0 H:2 mH:3 rdy:True natt:0
jadegolem CFM_712_t02 zp:4 e:105 A:2 H:2 mH:2 rdy:True natt:0
EnemyMinions:
ayablackpaw CFM_902 zp:1 e:49 A:6 H:4 mH:4 rdy:True natt:0 ex
jadegolem CFM_712_t05 zp:2 e:107 A:5 H:5 mH:5 rdy:True natt:0 ex
Own Handcards: 
pos 1 primalfintotem 2 entity 32 UNG_201 0 0 0
pos 2 maelstromportal 2 entity 20 KAR_073 0 0 0
pos 3 southseadeckhand 1 entity 13 CS2_146 0 0 0
pos 4 stormforgedaxe 2 entity 33 EX1_247 0 0 0
pos 5 primalfintotem 2 entity 31 UNG_201 0 0 0
pos 6 bloodlust 5 entity 19 CS2_046 0 0 0
Enemy cards: 4
ownDiedMinions: CS2_146,27;UNG_809,9;OG_028,29;UNG_809t1,85;CFM_637,5;CFM_712_t01,89;UNG_809,16;NEW1_009,86;UNG_809t1,92;EX1_595,14;EX1_565,11;EX1_575,15;CS2_065,97;OG_028,6;
enemyDiedMinions: UNG_928,78;CFM_712_t01,88;CFM_715,40;CFM_712_t02,90;CFM_712_t03,91;CFM_715,47;CFM_343,44;CFM_712_t04,93;hexfrog,101;
og: 823,1;893,1;2850,2;683,1;2230,2;2851,2;595,1;650,1;1710,1;2179,1;1263,1;1098,1;1236,1;1248,1;837,1;
eg: 788,1;2912,1;650,1;521,1;681,2;1073,1;651,1;652,1;519,1;653,1;1551,1;787,1;2242,1;2821,1;
td: EX1_246;EX1_008,2;CFM_707,2;CFM_715;CFM_902;CFM_637;EX1_565;CS2_046;
tdc: 10 tdc mismatch 9

**Comment by BongoBengt** [comment]
Last calc shows:

Best Board Actions:
play southseadeckhand id 13, pos 1

play bloodlust id 19, pos 1

attacker: manatidetotem id 25, enemy: druid id 82

attacker: jadegolem id 106, enemy: druid id 82

attacker: jadespirit id 28, enemy: druid id 82

attacker:  id 13, enemy: druid id 82

attacker: jadegolem id 105, enemy: druid id 82

attack with hero, enemy: druid id 82

**Comment by pazzl7** [comment]
southseadeckhand without weapon have no charge on this turn ;)

**Comment by BongoBengt** [comment]
You can see that it attacks:
**attacker: id 13, enemy: druid id 82**
