### ISSUE TITLE
AI doesn't detect deck config files

### ISSUE THREAD

**Issue by Marthisdil** [mvegter/OpenAI#12]
[Combo] Can't find _combo.txt, consider creating one!
[Combo] Can't find _combo.txt, consider creating one!
[Discovery] Can't find _discovery.txt, consider creating one!
[Mulligan] Can't find _mulligan.txt, consider creating one!
[Mulligan] Can't find _mulligan.txt, consider creating one!

the files exist in the deck's customconfig folder.

**Comment by mvegter** [comment]
Files for OpenAI should be in the OpenAI folder under data. The folder that you mention, customconfig, is for VisionAI. We are working on support for VisionAI's files, but it is not a high priority point for us.

**Comment by mvegter** [comment]
Closing issue. Reason: Invalid

**Comment by Marthisdil** [comment]
Oh!  I see - so does the AI only allow 1 deck?  If it can support
multiples, how do you configure them (i.e. with vision ai, in the
CustomConfig folders, you have a .ini pointing the AI files for which deck).

Thanks!

**Comment by mvegter** [comment]
Check the Decos folder on github. It is an example  of how the Data folder should look.

It checks like this:
1. Data / (Own Class) / (Deck Name) / (file)
2. Data / (Own Class) / (file)
3. Data / (file)
4. OpenAI / (file)

Which means you can have a deck specific mulligan but use the same settings file for all decks of that class.

**Comment by Marthisdil** [comment]
Thanks Martijn!
